// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSAG3GK5XAIQzmXn42m_SzWxHucQ0HbZY',
    appId: '1:1032371312271:web:525903b9be056a602102fa',
    messagingSenderId: '1032371312271',
    projectId: 'my-app-59551',
    authDomain: 'my-app-59551.firebaseapp.com',
    storageBucket: 'my-app-59551.appspot.com',
    measurementId: 'G-XTMGRYV2XG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeK5uvhXDdF2nTOSaXJYYBm9oOUyBNAq4',
    appId: '1:1032371312271:android:c32468db1527a8872102fa',
    messagingSenderId: '1032371312271',
    projectId: 'my-app-59551',
    storageBucket: 'my-app-59551.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHjID7HcXMpPxlVlaVzSKTlMUromzg5BU',
    appId: '1:1032371312271:ios:ebf2c1d3417d1cb32102fa',
    messagingSenderId: '1032371312271',
    projectId: 'my-app-59551',
    storageBucket: 'my-app-59551.appspot.com',
    androidClientId: '1032371312271-ifvmehit7fm8vlllcna8fdr2thjm77ev.apps.googleusercontent.com',
    iosClientId: '1032371312271-2iv7g9f0kb08b79seqd0vr5uf3mpab3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.shivomCreation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHjID7HcXMpPxlVlaVzSKTlMUromzg5BU',
    appId: '1:1032371312271:ios:670b8b4cc289a2792102fa',
    messagingSenderId: '1032371312271',
    projectId: 'my-app-59551',
    storageBucket: 'my-app-59551.appspot.com',
    androidClientId: '1032371312271-ifvmehit7fm8vlllcna8fdr2thjm77ev.apps.googleusercontent.com',
    iosClientId: '1032371312271-fsc16embf2nlcnercu60qs8hsued28ra.apps.googleusercontent.com',
    iosBundleId: 'com.example.shivomCreation.RunnerTests',
  );
}
